# Generated by Django 4.2.5 on 2025-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Search Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_query", models.CharField(db_index=True, max_length=255)),
                ("search_timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=500)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("price_text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("url", models.URLField(max_length=1000)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("weight", models.CharField(blank=True, max_length=100, null=True)),
                ("store", models.CharField(blank=True, max_length=255, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-search_timestamp", "price"],
                "indexes": [
                    models.Index(
                        fields=["search_query", "search_timestamp"],
                        name="shopping_pr_search__d57efa_idx",
                    ),
                    models.Index(fields=["brand"], name="shopping_pr_brand_b3ad02_idx"),
                    models.Index(fields=["price"], name="shopping_pr_price_86731a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CachedSearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=255)),
                ("results", models.JSONField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["query", "expires_at"],
                        name="shopping_ca_query_ccb16a_idx",
                    )
                ],
            },
        ),
    ]
